apiVersion: v1
kind: Secret
metadata:
    name: secret-using-sops
type: Opaque
data:
    password: ENC[AES256_GCM,data:ZCEQu7tkidmbTflXh5wUiA==,iv:EP+u6nMT0lNJ6KStaH+Hg2gvXte6aEpAy0h1Y2Gqfa0=,tag:rNdjI/MQh4Yz3AnZGoA1eA==,type:str]
sops:
    age:
        - recipient: age1hfs8mtsp4r82ak3sdj8ww52ehvy6g3gq3zpqhs0mjurzwase259sqelu76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNWZaenBVdjdmZzhudlYr
            Z05YalNaQUxPbFhZUXJIUVUwYXNvTHY1bldZCkNaNWV5a0JuY0tncVpERDFCS3Zj
            UnVSV3pZTWNYR2cxb1BTVUg2cDB3R1EKLS0tIHYydEZWZDN4bjQ1VVlFNHlYZ3ZP
            WktvQ1NVZGw1R2RCbmo2SW4vQW5FZ0UK2nEwBtdjBu1EJwBkcsa7wpmwfCszJKHc
            FgFlxdUbKzf2vgsUgqlXMNQbFaw1AG7T2GURF6sqWm2NW6qaTt1Btw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T11:20:21Z"
    mac: ENC[AES256_GCM,data:VEa6MuKmarZe+0gZDaam+wLhZv8MkFwdUT5+ywe1dGjlg9eSkJ6qtkRGRFskXSS8rVr6K6+jmcNrofxKbXKJm34hn/KgWa6JrmAyyYmD8aIpDqOQJRNcaqEQwakYqRD60U/C8/TeuYaGRb0LFZ9xOCQRirgDEBjpFHfF6uO66lk=,iv:U4q2lp1GK6/TTz2MAidJAhToAd6X8xhARlaSiNR9Lqg=,tag:WAHnyy1Q/HGGOjoR7p02hg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
